version: '3'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile.api
    container_name: ycm_api
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app/api
      - ./AI_meeting_by_Gradio:/app/AI_meeting_by_Gradio
      - ./utils:/app/utils
      - ./uploads:/app/uploads
      - ./temp:/app/temp
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ycm_frontend
    ports:
      - "80:80"
    depends_on:
      - api
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ycm_meeting_recorder
    ports:
      - "7860:7860"
    volumes:
      - ./data:/app/data
      - ./AI_meeting_by_Gradio/exports:/app/exports
      - ./AI_meeting_by_Gradio/uploads:/app/uploads
    environment:
      - OLLAMA_HOST=http://ollama:11434
      # 請在此處設置您的 OpenAI API 密鑰
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DOCKER_AUDIO_ENABLED=true
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_data:
    driver: local
